version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:11.1.0-browsers
    working_directory: /tmp/workspace
jobs:
  security-check:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: yarn audit
  test:
    executor: my-executor
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:coverage
      - persist_to_workspace:
          root: /tmp
          paths:
            - workspace
  sonar:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: yarn sonarqube
      - persist_to_workspace:
          root: /tmp
          paths:
            - workspace
  build:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: yarn build
      - persist_to_workspace:
          root: /tmp
          paths:
            - workspace
  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: git config --global user.email $GIT_EMAIL
      - run: git config --global user.name $GIT_NAME
      - add_ssh_keys:
          fingerprints:
            - "31:32:1d:d4:b1:b6:35:3d:47:e6:5f:39:e7:99:b7:77"
      - run: yarn deploy:gh-page
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - sonar:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - test
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - test
      - deploy:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - build
      - security-check:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - test
