version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.4-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  build:
    docker:
      - image: circleci/node:8.11.4-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: git config --global user.email $GIT_EMAIL
      - run: git config --global user.name $GIT_NAME
      - run: yarn deploy:gh-page
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - test
